import scrapy

class VehicleDetailsItem(scrapy.Item):
    Make = scrapy.Field()
    Model = scrapy.Field()
    Trim = scrapy.Field()
    Derivative = scrapy.Field()
    DerivativeTranslatedEnglish = scrapy.Field()
    Powertrain = scrapy.Field()
    VersionName = scrapy.Field()
    VersionNameTranslatedEnglish = scrapy.Field()
    Currency = scrapy.Field()
    Price = scrapy.Field()
    DeliveryCost = scrapy.Field()
    Country = scrapy.Field()
    Date = scrapy.Field()
    CustomerType = scrapy.Field()
    MonthlyPaymentType = scrapy.Field()
    ProductName = scrapy.Field()
    MonthlyPaymentProviderName = scrapy.Field()
    MonthlyPaymentProviderType = scrapy.Field()
    ContractDuration = scrapy.Field()
    YearlyMileageKm = scrapy.Field()
    YearlyMileageMiles = scrapy.Field()
    TotalContractMileageKm = scrapy.Field()
    TotalContractMileageMiles = scrapy.Field()
    DepositRetail = scrapy.Field()
    DepositPercentOfPrice = scrapy.Field()
    MonthlyPaymentEMI = scrapy.Field()
    DataSource = scrapy.Field()
    URL = scrapy.Field()
    OtherSource = scrapy.Field()
    VehiclePriceReference = scrapy.Field()
    NumberOfDoors = scrapy.Field()
    bodyType = scrapy.Field()
    builtoption = scrapy.Field()
    productdescription = scrapy.Field()
